/**
 * Per-window clientId, layered on top of the desktop-level client_id that
 * Rust generates in `prefs.json` via `prefs::ensure_identity`.
 *
 * Two-level identity:
 *
 *   desktopClientId — `prefs.client_id`, persistent per Tauri install.
 *     Generated once by Rust (`short_uuid`) on first launch. Identifies the
 *     desktop app instance regardless of which Android device is paired.
 *     Used for c-id headers, app-socket auth, upload signatures, etc.
 *     Shared across every webview the app spawns.
 *
 *   boundClientId — sessionStorage entry `__bound_client_id__`. When the user
 *     picks an Android device (or auto-binds via `?__cid=` from a parent
 *     window) we record that device's clientId here so API calls route to
 *     the right host/token. Empty when the app is in local mode.
 *
 * `getWindowClientId()` returns boundClientId ?? desktopClientId. This is
 * the value every consumer in this repo uses — call sites that need the
 * pure desktop identity (e.g. upload signatures) call `getDesktopClientId()`
 * directly.
 *
 * Local mode is purely a derived state: when boundClientId is empty,
 * `getWindowClientId()` falls back to desktopClientId, and `isLocalMode()`
 * reports true because boundClientId is empty.
 *
 * No more `LOCAL_CLIENT_ID` sentinel string. "Local mode" is the absence of
 * a bound device, not a magic id.
 */
import { get as prefsGet } from '@/lib/prefs'

const BOUND_KEY = '__bound_client_id__'
const WINDOW_ID_KEY = '__window_id__'

let cachedBound: string | null | undefined
let cachedWindowId: string | null

function readSession(key: string): string | null {
  try {
    return sessionStorage.getItem(key)
  } catch {
    return null
  }
}

function writeSession(key: string, value: string): void {
  try {
    if (value) sessionStorage.setItem(key, value)
    else sessionStorage.removeItem(key)
  } catch {
    // sessionStorage may be disabled (private mode quirks); fall through.
  }
}

/**
 * The persistent desktop clientId. Generated by Rust in `prefs::ensure_identity`
 * (`src-tauri/src/prefs.rs`) and exposed to the frontend via
 * `prefsGet('client_id')` — that prefs cache is hydrated at bootstrap by
 * `preloadPrefs()`.
 *
 * In web (non-Tauri) mode this is also populated by `main.ts` with a random
 * uuid on first run, so the same code path works in both modes.
 */
export function getDesktopClientId(): string {
  return prefsGet('client_id', '')
}

/**
 * The device this window is bound to, or '' for local mode.
 *
 * Bound at three points:
 *   - `applyUrlClientId()` — reads `?__cid=` from the URL (set by
 *     `openWindow` when spawning a child webview). Child webviews inherit
 *     their parent's binding automatically.
 *   - `useDeviceSessionsStore.setCurrent()` — user picks a device in the
 *     device switcher. Persisted in sessionStorage so the binding survives
 *     reload but is scoped to this window.
 *   - `useDeviceSessionsStore.remove()` — clears the binding if the active
 *     device was removed, dropping the window back to local mode.
 */
export function getBoundClientId(): string {
  if (cachedBound !== undefined) return cachedBound ?? ''
  const v = readSession(BOUND_KEY) ?? ''
  cachedBound = v
  return v
}

export function setBoundClientId(id: string): void {
  cachedBound = id
  writeSession(BOUND_KEY, id)
}

/** Clear the device binding — drops the window back to local mode. */
export function clearBoundClientId(): void {
  cachedBound = ''
  writeSession(BOUND_KEY, '')
}

/**
 * The effective clientId for this window: the bound device, or the desktop
 * id when no device is bound. This is what every `getCurrentClientId()` /
 * `isLocalMode()` consumer should read.
 */
export function getWindowClientId(): string {
  const bound = getBoundClientId()
  if (bound) return bound
  const desktop = getDesktopClientId()
  return desktop
}

/** True when no device is bound — i.e. local-only mode. */
export function isLocalMode(): boolean {
  return !getBoundClientId()
}

/**
 * True when the given id represents "this desktop, no device bound" — i.e.
 * matches the desktop clientId (or is empty, which would only happen if Rust
 * hasn't yet generated an identity).
 */
export function isLocalClientId(id: string): boolean {
  if (!id) return true
  const desktop = getDesktopClientId()
  return !desktop || id === desktop
}

/** Stable per-window id, used to filter self-broadcasts. */
export function getWindowId(): string {
  if (cachedWindowId) return cachedWindowId
  let id = readSession(WINDOW_ID_KEY)
  if (!id) {
    id = `w_${Math.random().toString(36).slice(2, 10)}_${Date.now().toString(36)}`
    writeSession(WINDOW_ID_KEY, id)
  }
  cachedWindowId = id
  return id
}

/**
 * Apply `?__cid=` from the current URL into sessionStorage.
 * Called once at app bootstrap (before pinia) so any later synchronous
 * `getBoundClientId()` reads the correct value.
 *
 * Skips the desktop clientId: a local-mode parent opens a child with
 * `?__cid=<desktopClientId>`, but the child must start in local mode
 * too. Treating the desktop id as "bound" would make `isLocalMode()`
 * lie in the child and `getCurrentAuthToken()` look up a clientId that
 * is not in the device sessions list → router guard → /login.
 */
export function applyUrlClientId(): void {
  try {
    const url = new URL(window.location.href)
    const cid = url.searchParams.get('__cid')
    if (!cid) return
    if (isLocalClientId(cid)) {
      // Strip the param without binding — child stays in local mode.
      url.searchParams.delete('__cid')
      const query = url.searchParams.toString()
      const next = url.pathname + (query ? `?${query}` : '') + url.hash
      window.history.replaceState({}, '', next)
      return
    }
    setBoundClientId(cid)
    url.searchParams.delete('__cid')
    const query = url.searchParams.toString()
    const next = url.pathname + (query ? `?${query}` : '') + url.hash
    window.history.replaceState({}, '', next)
  } catch {
    // non-DOM environment or weird URL
  }
}