#![cfg(test)]

//! Cross-platform crypto vector tests.
//!
//! Verifies that the Rust backend (p256 / ed25519-dalek / chacha20poly1305)
//! produces identical results to plain-app's Kotlin implementation
//! (BouncyCastle / Google Tink) for:
//!   • ECDH P-256 (secp256r1, X9.63 uncompressed public keys, SHA-256 derivation)
//!   • Ed25519 sign/verify (raw 32-byte keys, 64-byte signatures)
//!   • XChaCha20-Poly1305 (24-byte nonce, nonce || ciphertext || tag format)
//!   • base64 (RFC 4648) and lowercase hex encoding
//!
//! Vectors are generated by `CryptoVectorGenerator.kt` in plain-app's
//! `commonTest` and stored in `tests/fixtures/crypto-vectors.json`.

use serde::Deserialize;
use sha2::{Digest, Sha256};

use crate::utils::base64::{base64_decode, base64_encode};
use crate::utils::hex::bytes_to_hex;

const VECTORS_JSON: &str = include_str!("../../../tests/fixtures/crypto-vectors.json");

#[derive(Deserialize)]
struct Vectors {
    ecdh: EcdhVectors,
    ed25519: Ed25519Vectors,
    xchacha20: XChaChaVectors,
    base64: Base64Vectors,
    hex: HexVectors,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct EcdhVectors {
    private_key_a: String,
    public_key_a: String,
    private_key_b: String,
    public_key_b: String,
    shared_key: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Ed25519Vectors {
    private_key: String,
    public_key: String,
    message: String,
    signature: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct XChaChaVectors {
    key: String,
    nonce: String,
    plaintext: String,
    ciphertext: String,
}

#[derive(Deserialize)]
struct Base64Vectors {
    input: Vec<u8>,
    output: String,
}

#[derive(Deserialize)]
struct HexVectors {
    input: Vec<u8>,
    output: String,
}

fn vectors() -> Vectors {
    serde_json::from_str(VECTORS_JSON).expect("failed to parse crypto-vectors.json")
}

// ── ECDH P-256 ───────────────────────────────────────────────────────────────

#[test]
fn ecdh_shared_key_a_to_b_matches_vector() {
    let v = vectors().ecdh;
    let priv_a = base64_decode(&v.private_key_a);
    let pub_b = base64_decode(&v.public_key_b);
    assert_eq!(priv_a.len(), 32, "private key A must be 32 bytes");
    assert_eq!(pub_b.len(), 65, "public key B must be 65 bytes (X9.63)");
    assert_eq!(pub_b[0], 0x04, "public key B must start with 0x04");

    let secret = p256::SecretKey::from_slice(&priv_a).expect("invalid private key A");
    let public = p256::PublicKey::from_sec1_bytes(&pub_b).expect("invalid public key B");
    let shared = p256::ecdh::diffie_hellman(secret.to_nonzero_scalar(), public.as_affine());
    let derived = Sha256::digest(shared.raw_secret_bytes());

    let expected = base64_decode(&v.shared_key);
    assert_eq!(
        derived.as_slice(),
        expected.as_slice(),
        "ECDH(A_priv, B_pub) must match vector shared key"
    );
}

#[test]
fn ecdh_shared_key_b_to_a_matches_vector() {
    let v = vectors().ecdh;
    let priv_b = base64_decode(&v.private_key_b);
    let pub_a = base64_decode(&v.public_key_a);

    let secret = p256::SecretKey::from_slice(&priv_b).expect("invalid private key B");
    let public = p256::PublicKey::from_sec1_bytes(&pub_a).expect("invalid public key A");
    let shared = p256::ecdh::diffie_hellman(secret.to_nonzero_scalar(), public.as_affine());
    let derived = Sha256::digest(shared.raw_secret_bytes());

    let expected = base64_decode(&v.shared_key);
    assert_eq!(
        derived.as_slice(),
        expected.as_slice(),
        "ECDH(B_priv, A_pub) must match vector shared key (symmetry)"
    );
}

#[test]
fn ecdh_shared_key_base64_matches_vector() {
    let v = vectors().ecdh;
    let priv_a = base64_decode(&v.private_key_a);
    let pub_b = base64_decode(&v.public_key_b);

    let secret = p256::SecretKey::from_slice(&priv_a).expect("invalid private key A");
    let public = p256::PublicKey::from_sec1_bytes(&pub_b).expect("invalid public key B");
    let shared = p256::ecdh::diffie_hellman(secret.to_nonzero_scalar(), public.as_affine());
    let derived = Sha256::digest(shared.raw_secret_bytes());

    assert_eq!(
        base64_encode(&derived),
        v.shared_key,
        "base64-encoded shared key must match vector"
    );
}

// ── Ed25519 ──────────────────────────────────────────────────────────────────

#[test]
fn ed25519_verify_plain_app_signature() {
    let v = vectors().ed25519;
    assert_eq!(
        base64_decode(&v.public_key).len(),
        32,
        "public key must be 32 bytes"
    );
    assert_eq!(
        base64_decode(&v.signature).len(),
        64,
        "signature must be 64 bytes"
    );

    assert!(
        super::ed25519_verify(&v.public_key, v.message.as_bytes(), &v.signature),
        "Rust must verify plain-app's Ed25519 signature"
    );
}

#[test]
fn ed25519_rejects_tampered_signature() {
    let v = vectors().ed25519;
    let mut sig_bytes = base64_decode(&v.signature);
    sig_bytes[0] ^= 0x01;
    let tampered = base64_encode(&sig_bytes);

    assert!(
        !super::ed25519_verify(&v.public_key, v.message.as_bytes(), &tampered),
        "tampered signature must fail verification"
    );
}

#[test]
fn ed25519_rejects_tampered_message() {
    let v = vectors().ed25519;
    let tampered_msg = format!("{}!", v.message);

    assert!(
        !super::ed25519_verify(&v.public_key, tampered_msg.as_bytes(), &v.signature),
        "signature over a different message must fail verification"
    );
}

// ── XChaCha20-Poly1305 ───────────────────────────────────────────────────────

#[test]
fn xchacha20_decrypt_plain_app_ciphertext() {
    let v = vectors().xchacha20;
    let key = base64_decode(&v.key);
    let nonce = base64_decode(&v.nonce);
    let ciphertext = base64_decode(&v.ciphertext);

    assert_eq!(key.len(), 32, "key must be 32 bytes");
    assert_eq!(nonce.len(), 24, "nonce must be 24 bytes");
    assert_eq!(
        ciphertext.len(),
        v.plaintext.len() + 16,
        "ciphertext length must be plaintext + 16-byte tag"
    );

    // Reconstruct nonce || ciphertext blob (the format xchacha_decrypt_raw expects).
    let mut blob = Vec::with_capacity(nonce.len() + ciphertext.len());
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);

    let plaintext = super::xchacha_decrypt_raw(&key, &blob)
        .expect("decryption must succeed");
    assert_eq!(
        plaintext,
        v.plaintext.as_bytes(),
        "decrypted plaintext must match vector"
    );
}

#[test]
fn xchacha20_re_encrypt_produces_same_ciphertext() {
    let v = vectors().xchacha20;
    let key = base64_decode(&v.key);
    let nonce = base64_decode(&v.nonce);
    let expected_ct = base64_decode(&v.ciphertext);

    // Use the raw chacha20poly1305 crate directly to encrypt with the fixed nonce.
    use chacha20poly1305::aead::{Aead, KeyInit};
    let cipher = chacha20poly1305::XChaCha20Poly1305::new_from_slice(&key)
        .expect("invalid key");
    let nonce_obj = chacha20poly1305::XNonce::from_slice(&nonce);
    let re_encrypted = cipher
        .encrypt(nonce_obj, v.plaintext.as_bytes())
        .expect("encryption must succeed");

    assert_eq!(
        re_encrypted, expected_ct,
        "re-encrypting with the same key+nonce must produce the same ciphertext"
    );
}

#[test]
fn xchacha20_decrypt_rejects_wrong_key() {
    let v = vectors().xchacha20;
    let nonce = base64_decode(&v.nonce);
    let ciphertext = base64_decode(&v.ciphertext);
    let wrong_key = vec![0u8; 32];

    let mut blob = Vec::with_capacity(nonce.len() + ciphertext.len());
    blob.extend_from_slice(&nonce);
    blob.extend_from_slice(&ciphertext);

    assert!(
        super::xchacha_decrypt_raw(&wrong_key, &blob).is_none(),
        "decryption with wrong key must fail"
    );
}

// ── base64 ───────────────────────────────────────────────────────────────────

#[test]
fn base64_encodes_known_bytes() {
    let v = vectors().base64;
    assert_eq!(base64_encode(&v.input), v.output);
}

#[test]
fn base64_decodes_known_string() {
    let v = vectors().base64;
    assert_eq!(base64_decode(&v.output), v.input);
}

#[test]
fn base64_roundtrips_arbitrary_bytes() {
    let arbitrary = [0x00, 0x01, 0x02, 0xFE, 0xFF, 0x80, 0x40, 0x20];
    let encoded = base64_encode(&arbitrary);
    let decoded = base64_decode(&encoded);
    assert_eq!(decoded, arbitrary);
}

// ── hex ──────────────────────────────────────────────────────────────────────

#[test]
fn hex_encodes_known_bytes() {
    let v = vectors().hex;
    assert_eq!(bytes_to_hex(&v.input), v.output);
}

#[test]
fn hex_output_is_lowercase() {
    let v = vectors().hex;
    assert_eq!(v.output, v.output.to_lowercase());
}

#[test]
fn hex_encodes_full_byte_range() {
    let all_bytes: Vec<u8> = (0..=255u8).collect();
    let hex = bytes_to_hex(&all_bytes);
    assert_eq!(hex.len(), 512);
    assert!(hex.chars().all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
    assert_eq!(&hex[0..2], "00");
    assert_eq!(&hex[510..512], "ff");
}
